### PR TITLE
fix never ending page load

### PR DESCRIPTION
**Pull request by xmacan**

### CODE REVIEW

**Comment by TheWitness** [comment]
Help me out on this one.  Did you not have a config.php set?

**Comment by xmacan** [comment]
I have $flowview_use_cacti_db = true;

**Comment by TheWitness** [comment]
I have the same.  So, this is a red herring.

**Comment by xmacan** [comment]
ok, I will test it today on fresh install

**Comment by xmacan** [comment]
maybe problem on my side. Actual flowview has compatibiity cacti 1.2.27. I tested on 1.2.26.

**Comment by TheWitness** [comment]
Yea, you need to update `lib/database.php` until 1.2.28 is released.

**Comment by xmacan** [comment]
maybe we should warn (or disable installing) plugins if INFO compatibility is not met

**Comment by TheWitness** [comment]
We should make it 1.2.28.  I can stage Cacti tomorrow.  I'm working a big re-index bug with a user right now though.  So, release is likely still a bit off.

**Pull request closed without merging**
