### PR TITLE
fix save panel checkboxes

### PR DESCRIPTION
**Pull request by xmacan**
@TheWitness there is still small issue: Panel_table is saved to db correctly  but on web is still displayed as checked. Maybe due to default 'on' value. I haven't time to solve it now

### CODE REVIEW

**Comment by TheWitness** [comment]
The request variables here do not contain `panel_`.  So, this pull request does not resolve this problem.

**Comment by xmacan** [comment]
It resolves filter definition.

**Comment by TheWitness** [comment]
I was going to post this to show you what it look like, and then I see the problem.  Let me know if you can see it too?

image

**Comment by xmacan** [comment]
Without this, checkboxes in console -> flowview -> filters are not saved  when createing or editing filter

**Comment by TheWitness** [comment]
Oh, let me check that.  I'm still waking up ;)

**Comment by xmacan** [comment]
don't hurry, start with coffee! :-D

**Review by TheWitness — APPROVED** [review]

**Pull request merged**
